#!/usr/bin/env bash

CC=$SNAP_DATA/custom_components

cp -rf "${SNAP}/hacs" "${CC}"
if [ $? -ne 0 ]; then
    logger "Failed to copy data"
else
    logger "Copied ${SNAP_NAME} data to Home Assistant:"
    logger "From:     $SNAP/hacs -"
    logger "To:       $CC/hacs"
fi
